scan_results:
  default_dir: outputs/scan_results
  recent_file: ''
stock_data:
  search_paths:
  - /home/yu/PycharmProjects/Trade_Strategy/datasets/pkls
ui:
  display_options:
    show_bt_score: false
    show_peak_score: false
  left_panel_weight: 0.3
  right_panel_weight: 0.7
  stock_list_columns:
    column_labels:
      active_peaks:
        display: A.Pks
        tooltip: 'Active Peaks: Number of currently active peak points'
      avg_quality:
        display: Avg Q
        tooltip: 'Avg Quality: Average quality score of all breakthroughs'
      max_quality:
        display: Max Q
        tooltip: 'Max Quality: Maximum quality score among all breakthroughs'
      symbol:
        display: Sym
        tooltip: 'Symbol: Stock ticker symbol'
      total_breakthroughs:
        display: Bts
        tooltip: 'Breakthroughs: Total number of breakthroughs detected'
    column_priority:
    - total_breakthroughs
    - active_peaks
    - avg_quality
    - max_quality
    columns_enabled: true
    visible_columns:
    - avg_quality
    - max_quality
  window_height: 900
  window_width: 1600
