scan_results:
  default_dir: outputs/scan_results
  recent_file: ''
scan_settings:
  end_date: null
  start_date: '2024-01-01'
  use_json_time_range: true
stock_data:
  search_paths:
  - /home/yu/PycharmProjects/Trade_Strategy/datasets/pkls
ui:
  colors:
    breakthrough_marker: '#0000FF'
    breakthrough_text_bg: '#FFFFFF'
    breakthrough_text_score: '#FF0000'
    candlestick_down: '#B71C1C'
    candlestick_up: '#4CAF50'
    peak_marker: '#000000'
    peak_text_id: '#000000'
    peak_text_score: '#969696'
    resistance_zone: '#5D5932'
    volume_down: '#696969'
    volume_highlight: '#FFD700'
    volume_up: '#D3D3D3'
  display_options:
    show_bt_score: false
    show_peak_score: false
  left_panel_weight: 0.3
  right_panel_weight: 0.7
  stock_list_columns:
    column_labels:
      active_peaks: Active Peaks
      avg_quality: Avg Quality
      bts: Breakthroughs
      max_quality: Max Quality
    column_priority:
    - bts
    - active_peaks
    - avg_quality
    - max_quality
    columns_enabled: false
    visible_columns:
    - bts
    - active_peaks
    - max_quality
  window_height: 900
  window_width: 1600
